// ===== Countries: one list for the whole Student Hub =====
// [ISO 3166-1 alpha-2 code, name shown on the site, geographically in Europe]
// Used by the registration form (join.js: country suggestions) and the Students explorer (map, filters).
// Names: the Student Hub's own list. Codes: ISO 3166-1 alpha-2 (Kosovo uses the common user code "XK").
// "In Europe" follows Natural Earth's CONTINENT field (v5.1.2), so it is GEOGRAPHY only: it says nothing
// about EU/EEA/Swiss citizenship, which is never inferred from a country (docs/students-explorer.md).
// Countries too small for the 1:50m map (7): LI, MV, MC, KN, SM, TO, TV. They are still in the
// country list and filters, only not drawn.
const EUHEM_COUNTRY_ROWS = [
  ["AF", "Afghanistan", false],
  ["AL", "Albania", true],
  ["DZ", "Algeria", false],
  ["AD", "Andorra", true],
  ["AO", "Angola", false],
  ["AG", "Antigua and Barbuda", false],
  ["AR", "Argentina", false],
  ["AM", "Armenia", false],
  ["AU", "Australia", false],
  ["AT", "Austria", true],
  ["AZ", "Azerbaijan", false],
  ["BS", "Bahamas", false],
  ["BH", "Bahrain", false],
  ["BD", "Bangladesh", false],
  ["BB", "Barbados", false],
  ["BY", "Belarus", true],
  ["BE", "Belgium", true],
  ["BZ", "Belize", false],
  ["BJ", "Benin", false],
  ["BT", "Bhutan", false],
  ["BO", "Bolivia", false],
  ["BA", "Bosnia and Herzegovina", true],
  ["BW", "Botswana", false],
  ["BR", "Brazil", false],
  ["BN", "Brunei", false],
  ["BG", "Bulgaria", true],
  ["BF", "Burkina Faso", false],
  ["BI", "Burundi", false],
  ["CV", "Cabo Verde", false],
  ["KH", "Cambodia", false],
  ["CM", "Cameroon", false],
  ["CA", "Canada", false],
  ["CF", "Central African Republic", false],
  ["TD", "Chad", false],
  ["CL", "Chile", false],
  ["CN", "China", false],
  ["CO", "Colombia", false],
  ["KM", "Comoros", false],
  ["CG", "Congo", false],
  ["CR", "Costa Rica", false],
  ["CI", "Côte d’Ivoire", false],
  ["HR", "Croatia", true],
  ["CU", "Cuba", false],
  ["CY", "Cyprus", false],
  ["CZ", "Czechia", true],
  ["CD", "Democratic Republic of the Congo", false],
  ["DK", "Denmark", true],
  ["DJ", "Djibouti", false],
  ["DM", "Dominica", false],
  ["DO", "Dominican Republic", false],
  ["EC", "Ecuador", false],
  ["EG", "Egypt", false],
  ["SV", "El Salvador", false],
  ["GQ", "Equatorial Guinea", false],
  ["ER", "Eritrea", false],
  ["EE", "Estonia", true],
  ["SZ", "Eswatini", false],
  ["ET", "Ethiopia", false],
  ["FJ", "Fiji", false],
  ["FI", "Finland", true],
  ["FR", "France", true],
  ["GA", "Gabon", false],
  ["GM", "Gambia", false],
  ["GE", "Georgia", false],
  ["DE", "Germany", true],
  ["GH", "Ghana", false],
  ["GR", "Greece", true],
  ["GD", "Grenada", false],
  ["GT", "Guatemala", false],
  ["GN", "Guinea", false],
  ["GW", "Guinea-Bissau", false],
  ["GY", "Guyana", false],
  ["HT", "Haiti", false],
  ["HN", "Honduras", false],
  ["HU", "Hungary", true],
  ["IS", "Iceland", true],
  ["IN", "India", false],
  ["ID", "Indonesia", false],
  ["IR", "Iran", false],
  ["IQ", "Iraq", false],
  ["IE", "Ireland", true],
  ["IL", "Israel", false],
  ["IT", "Italy", true],
  ["JM", "Jamaica", false],
  ["JP", "Japan", false],
  ["JO", "Jordan", false],
  ["KZ", "Kazakhstan", false],
  ["KE", "Kenya", false],
  ["KI", "Kiribati", false],
  ["XK", "Kosovo", true],
  ["KW", "Kuwait", false],
  ["KG", "Kyrgyzstan", false],
  ["LA", "Laos", false],
  ["LV", "Latvia", true],
  ["LB", "Lebanon", false],
  ["LS", "Lesotho", false],
  ["LR", "Liberia", false],
  ["LY", "Libya", false],
  ["LI", "Liechtenstein", true],
  ["LT", "Lithuania", true],
  ["LU", "Luxembourg", true],
  ["MG", "Madagascar", false],
  ["MW", "Malawi", false],
  ["MY", "Malaysia", false],
  ["MV", "Maldives", false],
  ["ML", "Mali", false],
  ["MT", "Malta", true],
  ["MH", "Marshall Islands", false],
  ["MR", "Mauritania", false],
  ["MU", "Mauritius", false],
  ["MX", "Mexico", false],
  ["FM", "Micronesia", false],
  ["MD", "Moldova", true],
  ["MC", "Monaco", true],
  ["MN", "Mongolia", false],
  ["ME", "Montenegro", true],
  ["MA", "Morocco", false],
  ["MZ", "Mozambique", false],
  ["MM", "Myanmar", false],
  ["NA", "Namibia", false],
  ["NR", "Nauru", false],
  ["NP", "Nepal", false],
  ["NL", "Netherlands", true],
  ["NZ", "New Zealand", false],
  ["NI", "Nicaragua", false],
  ["NE", "Niger", false],
  ["NG", "Nigeria", false],
  ["KP", "North Korea", false],
  ["MK", "North Macedonia", true],
  ["NO", "Norway", true],
  ["OM", "Oman", false],
  ["PK", "Pakistan", false],
  ["PW", "Palau", false],
  ["PS", "Palestine", false],
  ["PA", "Panama", false],
  ["PG", "Papua New Guinea", false],
  ["PY", "Paraguay", false],
  ["PE", "Peru", false],
  ["PH", "Philippines", false],
  ["PL", "Poland", true],
  ["PT", "Portugal", true],
  ["QA", "Qatar", false],
  ["RO", "Romania", true],
  ["RU", "Russia", true],
  ["RW", "Rwanda", false],
  ["KN", "Saint Kitts and Nevis", false],
  ["LC", "Saint Lucia", false],
  ["VC", "Saint Vincent and the Grenadines", false],
  ["WS", "Samoa", false],
  ["SM", "San Marino", true],
  ["ST", "São Tomé and Príncipe", false],
  ["SA", "Saudi Arabia", false],
  ["SN", "Senegal", false],
  ["RS", "Serbia", true],
  ["SC", "Seychelles", false],
  ["SL", "Sierra Leone", false],
  ["SG", "Singapore", false],
  ["SK", "Slovakia", true],
  ["SI", "Slovenia", true],
  ["SB", "Solomon Islands", false],
  ["SO", "Somalia", false],
  ["ZA", "South Africa", false],
  ["KR", "South Korea", false],
  ["SS", "South Sudan", false],
  ["ES", "Spain", true],
  ["LK", "Sri Lanka", false],
  ["SD", "Sudan", false],
  ["SR", "Suriname", false],
  ["SE", "Sweden", true],
  ["CH", "Switzerland", true],
  ["SY", "Syria", false],
  ["TW", "Taiwan", false],
  ["TJ", "Tajikistan", false],
  ["TZ", "Tanzania", false],
  ["TH", "Thailand", false],
  ["TL", "Timor-Leste", false],
  ["TG", "Togo", false],
  ["TO", "Tonga", false],
  ["TT", "Trinidad and Tobago", false],
  ["TN", "Tunisia", false],
  ["TR", "Türkiye", false],
  ["TM", "Turkmenistan", false],
  ["TV", "Tuvalu", false],
  ["UG", "Uganda", false],
  ["UA", "Ukraine", true],
  ["AE", "United Arab Emirates", false],
  ["GB", "United Kingdom", true],
  ["US", "United States", false],
  ["UY", "Uruguay", false],
  ["UZ", "Uzbekistan", false],
  ["VU", "Vanuatu", false],
  ["VA", "Vatican City", true],
  ["VE", "Venezuela", false],
  ["VN", "Vietnam", false],
  ["YE", "Yemen", false],
  ["ZM", "Zambia", false],
  ["ZW", "Zimbabwe", false]
];

const EUHEM_COUNTRIES = EUHEM_COUNTRY_ROWS.map(([code, name, europe]) => ({ code, name, europe }));
const EUHEM_COUNTRY_BY_CODE = Object.fromEntries(EUHEM_COUNTRIES.map((c) => [c.code, c]));

// "Italy" -> "IT" (exact name from the list, or null)
function countryCodeOf(name) {
  const found = EUHEM_COUNTRIES.find((c) => c.name === name);
  return found ? found.code : null;
}

if (typeof module !== "undefined") module.exports = { EUHEM_COUNTRIES, EUHEM_COUNTRY_BY_CODE, countryCodeOf };
