/* Student Toolkit v3 — a local educational workspace. No AI service or data uploads. */
(function(){
  'use strict';
  const C=window.ToolkitSolveCore,F=window.ToolkitFormulas,root=document.getElementById('tk2-solve');if(!C||!F||!root)return;
  const $=id=>root.querySelector('#'+id);
  const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fmt=(v,d=5)=>v===null?'Undefined':!Number.isFinite(v)?'Outside numeric limits':v!==0&&(Math.abs(v)<1e-5||Math.abs(v)>1e8)?v.toExponential(4):Number(v.toFixed(d)).toString();
  const link=(url,text)=>`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(text)} ↗</a>`;
  const field=(id,label,value,attrs='')=>`<label class="sv-field" for="${id}"><span>${label}</span><input id="${id}" type="number" step="any" inputmode="decimal" value="${value}" ${attrs}></label>`;
  const select=(id,label,options)=>`<label class="sv-field" for="${id}"><span>${label}</span><select id="${id}">${options.map(([v,t])=>`<option value="${v}">${t}</option>`).join('')}</select></label>`;
  const pair=html=>`<div class="sv-fields">${html}</div>`;
  const metrics=a=>`<div class="sv-metrics">${a.map(([title,value])=>`<div><span>${esc(title)}</span><strong>${esc(value)}</strong></div>`).join('')}</div>`;
  const step=(n,title,formula,explanation)=>`<article class="sv-step"><span class="sv-step-number">0${n}</span><div><h4>${esc(title)}</h4><pre>${esc(formula)}</pre><p>${esc(explanation)}</p></div></article>`;
  const note=text=>`<aside class="sv-note">${esc(text)}</aside>`;
  const source=(url,label)=>`<p class="sv-source">Method reference: ${link(url,label)}</p>`;
  const query=new URLSearchParams(location.search);let booting=true,solver='finder',healthMode='cea',recipe='normal-between',lastQALY=null,lastFormula='',lastEconValid=false;
  const solverNames={finder:'Statistical Test Finder',excel:'Excel Formula Assistant',health:'Health Economics Calculator'};
  root.innerHTML=`<header class="sv-heading"><div><p class="tk-eyebrow">STUDENT TOOLKIT / SOLVE A PROBLEM</p><h2 id="tk2-solve-title" tabindex="-1">From “where do I start?”<br>to <em>“now I understand.”</em></h2><p>Choose the method. Find the formula. Explore the trade-off.<br>Three tools that turn a study question into a clear next step.</p></div><span class="sv-release">New · academic tools</span></header>
    <section class="sv-search-box" aria-labelledby="sv-search-title"><h3 id="sv-search-title">Start with what you need to do.</h3><form id="sv-question-form" role="search"><label for="sv-question" class="tk-sr-only">Describe your study task</label><input id="sv-question" type="search" maxlength="240" placeholder="Try: compare paired groups, find an Excel formula, calculate ICER…" autocomplete="off"><button type="submit" class="tk-button">Find a starting point →</button></form><p class="sv-small">Local topic matching, not an AI solver. It does not read your data or decide which assumptions hold.</p><div class="sv-prompts"><button type="button" data-prompt="confidence interval for a mean">Estimate a mean</button><button type="button" data-prompt="compare paired before after">Before &amp; after</button><button type="button" data-prompt="Excel formula variance">Check Excel working</button><button type="button" data-prompt="cost-effectiveness ICER">Compare costs &amp; effects</button></div><div id="sv-matches" aria-live="polite"></div></section>
    <nav class="sv-nav" aria-label="Problem-solving tools">${Object.entries(solverNames).map(([id,title],i)=>`<button type="button" data-solver="${id}" aria-pressed="${i===0}" aria-controls="sv-${id}"><span>0${i+1}</span><div><strong>${title}</strong><small>${['Find a suitable route','52 worked formula recipes','ICER · QALYs · discounting'][i]}</small></div><b aria-hidden="true">↗</b></button>`).join('')}</nav>
    <div class="sv-top-actions"><p>Educational support. Check assumptions and follow your course’s assessment rules.</p><button type="button" id="sv-copy-link" class="tk-text-button">Copy tool link</button><button type="button" id="sv-print" class="tk-text-button">Print working</button></div>
    <section id="sv-finder" aria-labelledby="sv-finder-title"><div class="sv-section-title"><p class="tk-eyebrow">FIRST THE DESIGN, THEN THE CALCULATION</p><h3 id="sv-finder-title" tabindex="-1">Find a method you can justify.</h3></div><div class="sv-workspace"><form id="sv-finder-form" class="sv-card sv-controls" novalidate>
      ${select('sv-course','Use course links for',[['fundamentals','Fundamentals of Statistics'],['statistics','Statistics for Healthcare']])}
      ${select('sv-goal','1. What is your goal?',[['test','Test a population claim'],['estimate','Estimate a parameter / interval'],['describe','Summarise a numeric dataset'],['probability','Find a probability under a model']])}
      <div id="sv-inference-fields">${select('sv-outcome','2. What is the outcome?',[['numeric','Numeric: focus on a mean'],['binary','Binary: focus on a proportion'],['other','Ordinal, multicategory, counts or survival']])}
      ${select('sv-groups','3. How many groups / measurements?',[['one','One sample / one parameter'],['two','Two groups or two measurements'],['many','Three or more']])}
      ${select('sv-design','4. What is the design?',[['independent','Independent observations / groups'],['paired','Matched pairs / one before-after pair'],['complex','Clustered, weighted or repeated beyond a pair'],['unsure','I am not sure']])}
      <div id="sv-n-fields">${pair(field('sv-n','Sample size / number of pairs',25,'min="1" step="1"')+`<div id="sv-n2-wrap">${field('sv-n2','Group 2 sample size',30,'min="2" step="1"')}</div>`)}</div>
      <div id="sv-model-wrap">${select('sv-model','5. Is the mean-model approximation justified?',[['reasonable','Assume reasonable for this teaching exercise'],['uncertain','I have not checked'],['poor','Strong problems / not justified']])}</div>
      <div id="sv-sd-wrap">${select('sv-sd','6. What SD information is available?',[['sample','Sample s; population σ is unknown'],['known','Population σ is explicitly known'],['unsure','I am not sure']])}</div>
      <div id="sv-k-wrap">${field('sv-k','Observed successes · k',12,'min="0" step="1"')}</div><div id="sv-p0-wrap">${field('sv-p0','Null proportion · π₀',.5,'min="0" max="1"')}</div></div>
      <p id="sv-finder-error" class="sv-error" role="alert" hidden></p><button type="submit" class="tk-button">Show the route →</button><p class="sv-small">The link opens the existing Lab with the chosen method and sample size. You still enter the remaining exercise values there.</p></form><div id="sv-finder-result" class="sv-card sv-result"></div></div></section>
    <section id="sv-excel" aria-labelledby="sv-excel-title" hidden><div class="sv-section-title"><p class="tk-eyebrow">UNDERSTAND WHAT THE FUNCTION RETURNS</p><h3 id="sv-excel-title" tabindex="-1">A formula, its inputs, and a worked example.</h3></div><div class="sv-workspace sv-excel-layout"><div class="sv-card sv-controls"><label class="sv-field" for="sv-formula-search"><span>Search the 52 recipes</span><input id="sv-formula-search" type="search" maxlength="120" placeholder="Try: variance, margin, NPV…"></label>${select('sv-formula-category','Topic',[['all','All topics'],...F.categories.map(v=>[v,v])])}<p id="sv-recipe-count" class="sv-small" role="status"></p><div id="sv-recipe-list" class="sv-recipe-list" aria-label="Formula recipes"></div></div><div class="sv-card sv-result"><div id="sv-formula-intro"></div><form id="sv-formula-form" novalidate><div class="sv-fields"><label class="sv-field" for="sv-range"><span>Primary range · R</span><input id="sv-range" value="A2:A8" maxlength="40" spellcheck="false"></label><label class="sv-field" for="sv-second"><span>Second range · S</span><input id="sv-second" value="B2:B8" maxlength="40" spellcheck="false"></label></div>${pair(select('sv-separator','Argument separator',[[',','Comma ,'],[';','Semicolon ;']])+select('sv-decimal','Decimal separator',[['.','Point .'],[',','Comma ,']]))}<p class="sv-small">English function names remain unchanged. This adapts separators, not translated function names or the settings of your workbook.</p><p id="sv-formula-error" class="sv-error" role="alert" hidden></p><button type="submit" class="tk-text-button">Update formula</button></form><pre id="sv-formula-output" class="sv-formula-output" tabindex="0" aria-label="Copyable Excel formula"></pre><div class="sv-inline-actions"><button id="sv-copy-formula" type="button" class="tk-button">Copy formula</button><button id="sv-copy-data" type="button" class="tk-text-button">Copy example columns (TSV)</button></div><div id="sv-formula-example"></div></div></div></section>
    <section id="sv-health" aria-labelledby="sv-health-title" hidden><div class="sv-section-title"><p class="tk-eyebrow">HEALTH ECONOMICS / TEACHING MODELS</p><h3 id="sv-health-title" tabindex="-1">Make the trade-off visible.</h3></div><div class="sv-health-tabs" role="group" aria-label="Economic calculation"><button type="button" data-health="cea" aria-pressed="true">Cost-effectiveness</button><button type="button" data-health="qaly" aria-pressed="false">QALY builder</button><button type="button" data-health="discount" aria-pressed="false">Discount future values</button></div>
      <div class="sv-workspace"><div class="sv-card sv-controls"><form id="sv-cea-form" novalidate><p class="tk-eyebrow">A: NEW OPTION / B: COMPARATOR</p>${pair(field('sv-ca','Option A cost',14000)+field('sv-cb','Option B cost',10000))}${pair(field('sv-ea','Option A QALYs',2.4)+field('sv-eb','Option B QALYs',2))}${field('sv-lambda','Threshold λ · monetary units / QALY',20000,'min="0"')}${select('sv-currency','Display currency (no conversion)',[['units','Monetary units'],['EUR','EUR'],['NOK','NOK']])}<p class="sv-small">Enter comparable totals or per-person quantities. Costs, effects, perspective, currency, price year and time horizon must match. Higher effects are better. Any discounting must already be reflected in these totals.</p><div class="sv-prompts"><button type="button" data-scenario="base">Trade-off</button><button type="button" data-scenario="dominant">Dominant</button><button type="button" data-scenario="dominated">Dominated</button><button type="button" data-scenario="southwest">Less cost, less effect</button></div></form>
      <form id="sv-qaly-form" novalidate hidden><label class="sv-field" for="sv-qaly-data"><span>Years, utility A, utility B · one row per period</span><textarea id="sv-qaly-data" rows="6" spellcheck="false">2, 0.8, 0.7\n3, 0.6, 0.5</textarea></label><p class="sv-small">Utilities are constant within each consecutive period and already describe time alive. The same time intervals are used for both options. No survival or state-transition model is fitted.</p><p class="sv-small">This teaching tool accepts utility weights from −1 to 1, including states valued below death. That is an input limit, not a universal instrument range. QALYs do not describe a person’s worth.</p></form>
      <form id="sv-discount-form" novalidate hidden>${pair(field('sv-rc','Annual cost discount rate (%)',3,'min="0" max="100"')+field('sv-re','Annual effect discount rate (%)',3,'min="0" max="100"'))}<label class="sv-field" for="sv-discount-data"><span>Year, cost, QALYs · one row per dated flow</span><textarea id="sv-discount-data" rows="6" spellcheck="false">0, 10000, 0\n1, 500, 0.8\n2, 500, 0.8\n3, 500, 0.8</textarea></label><p class="sv-small">Year 0 is now; year 1 is the end of the first year. Rates are illustrative, not a national policy recommendation. Enter discount rates from the relevant exercise or guidance. No half-cycle correction is applied.</p></form>
      <p id="sv-health-error" class="sv-error" role="alert" hidden></p><button id="sv-health-calculate" type="button" class="tk-button">Calculate &amp; explain →</button><p class="sv-small">Use anonymous, hypothetical inputs. This simplified comparison does not establish clinical suitability, equity, uncertainty or affordability.</p></div><div id="sv-health-result" class="sv-card sv-result"></div></div><div class="sv-inline-actions sv-after"><button type="button" id="sv-copy-working" class="tk-text-button">Copy worked result</button><button type="button" id="sv-apply-qaly" class="tk-button tk-button-outline" hidden>Use these QALYs in the comparison →</button></div></section>
    <details id="sv-practice" class="sv-practice"><summary>Try it yourself · 3 original mini-exercises</summary><p class="sv-small">Choose an answer before checking the explanation. Practice only; no grades or progress are stored.</p><div id="sv-practice-items"></div></details>
    <details class="sv-methods"><summary>Scope, privacy &amp; sources</summary><p>These original student-made tools provide educational routes and calculations, not a statistical analysis plan or a healthcare recommendation. The method chooser uses explicit rules, not AI. It does not inspect raw data. External reporting requirements and course rules take priority.</p><p>The Excel assistant generates formulas and shows fixed examples, but does not run Microsoft Excel or access your workbook. Custom ranges change the formula only. The health-economics tools use deterministic point estimates: no probabilistic sensitivity analysis, cost-effectiveness acceptability curve, extended dominance, survival model or budget-impact model is implemented.</p><p>Calculation inputs stay in this page session. No new storage key or remote API is used. Copy tool link shares only the tool/recipe/mode, not your values or datasets. Copy working can include your entered summaries; treat it accordingly.</p><p>Primary method references: ${link(C.refs.mean,'NIST: mean inference')} · ${link(C.refs.two,'NIST: independent and paired comparisons')} · ${link(C.refs.proportion,'NIST: proportion tests')} · ${link(C.refs.nmb,'York Health Economics Consortium: net monetary benefit')} · ${link(C.refs.qaly,'York Health Economics Consortium: QALYs')} · ${link(C.refs.excel,'Microsoft: statistical functions')} · ${link(C.refs.npv,'Microsoft: NPV timing')}.</p></details>
    <p id="sv-status" class="sv-status" role="status" aria-live="polite"></p><div id="sv-clipboard" class="sv-card" hidden><label class="sv-field" for="sv-copy-text"><span>Automatic copying is unavailable. Select and copy:</span><textarea id="sv-copy-text" rows="5" readonly></textarea></label><button type="button" id="sv-copy-close" class="tk-text-button">Close</button></div>`;
  // A template literal's literal backslash-n above becomes the intended line breaks.
  const read=id=>{const input=$(id),n=input.value.trim()===''?NaN:Number(input.value);input.removeAttribute('aria-invalid');if(!Number.isFinite(n)){input.setAttribute('aria-invalid','true');throw new Error('Enter a finite number for '+input.closest('label').querySelector('span').textContent+'. Blank is not zero.');}return n;};
  function syncURL(){if(booting)return;const url=new URL(location.href);if(url.searchParams.get('section')!=='solve')return;url.searchParams.set('solver',solver);if(solver==='excel')url.searchParams.set('recipe',recipe);else url.searchParams.delete('recipe');if(solver==='health')url.searchParams.set('mode',healthMode);else url.searchParams.delete('mode');history.replaceState(null,'',url.href);}
  function setSolver(key,focus=false){if(!Object.hasOwn(solverNames,key))key='finder';solver=key;for(const id of Object.keys(solverNames)){$('sv-'+id).hidden=id!==key;root.querySelector(`[data-solver="${id}"]`).setAttribute('aria-pressed',String(id===key));}if(focus)$('sv-'+key+'-title').focus();syncURL();}
  function finder(){
    const goal=$('sv-goal').value,outcome=$('sv-outcome').value,groups=$('sv-groups').value,design=$('sv-design').value;
    $('sv-inference-fields').hidden=['describe','probability'].includes(goal);
    $('sv-n2-wrap').hidden=groups!=='two'||design!=='independent'||outcome!=='numeric';
    $('sv-model-wrap').hidden=outcome!=='numeric';$('sv-sd-wrap').hidden=outcome!=='numeric'||groups!=='one'||design!=='independent';
    $('sv-k-wrap').hidden=outcome!=='binary'||groups!=='one';$('sv-p0-wrap').hidden=outcome!=='binary'||groups!=='one'||goal!=='test';
    try{
      const state={course:$('sv-course').value,goal,outcome,groups,design,model:$('sv-model').value,sd:$('sv-sd').value};
      const supported=['estimate','test'].includes(goal)&&outcome!=='other'&&groups!=='many'&&!['complex','unsure'].includes(design)&&!(design==='paired'&&groups!=='two');
      if(supported){state.n=read('sv-n');if(!$('sv-n2-wrap').hidden)state.n2=read('sv-n2');if(!$('sv-k-wrap').hidden)state.k=read('sv-k');if(!$('sv-p0-wrap').hidden)state.p0=read('sv-p0');}
      const r=C.chooseMethod(state);$('sv-finder-error').hidden=true;
      const checks=r.checks.map(t=>`<li>${esc(t)}</li>`).join('');
      $('sv-finder-result').innerHTML=`<span class="sv-route-status ${r.href?'':'sv-route-review'}">${r.status==='ready'?'A route to check':r.status==='supplementary'?'Supplementary method':'Pause & review'}</span><h3>${esc(r.title)}</h3><div class="sv-reasons">${r.why.map((w,i)=>`<p><span>0${i+1}</span>${esc(w)}</p>`).join('')}</div><h4>Before you use it</h4><ul class="sv-checks">${checks}</ul>${r.href?`<a class="tk-button" href="${esc(r.href)}" id="sv-open-lab">Open the matching Lab tool →</a><p class="sv-small">Method and sample size are passed on. The remaining fields initially contain demonstration values; replace them with your own exercise values.</p>`:note('No calculator is launched for this route. Clarify the issue or use a suitable validated package with instructor guidance.')}<p class="sv-small">${esc(r.warning)}</p>${source(r.source,'NIST methods')}`;
      $('sv-status').textContent=r.title;return true;
    }catch(e){$('sv-finder-error').textContent=e.message;$('sv-finder-error').hidden=false;$('sv-finder-result').replaceChildren();return false;}
  }
  function filterRecipes(){const rows=F.search($('sv-formula-search').value,$('sv-formula-category').value);$('sv-recipe-count').textContent=rows.length+' matching recipes';$('sv-recipe-list').innerHTML=rows.map(r=>`<button type="button" data-recipe="${r.id}" aria-pressed="${recipe===r.id}"><strong>${esc(r.title)}</strong><span>${esc(r.category)}</span></button>`).join('')||'<p class="sv-small">No matching recipe. Try a shorter term or another topic.</p>';}
  function selectRecipe(id){if(!F.byId.has(id))id='normal-between';recipe=id;const r=F.byId.get(id);$('sv-formula-intro').innerHTML=`<p class="tk-eyebrow">${esc(r.category)} / WORKED RECIPE</p><h3>${esc(r.title)}</h3><p>${esc(r.why)}</p>`;
    $('sv-range').disabled=!r.template.includes('{R}');$('sv-second').disabled=!r.template.includes('{S}');
    $('sv-copy-data').hidden=!r.template.includes('{R}');
    $('sv-formula-example').innerHTML=`<div class="sv-example"><span class="tk-eyebrow">FIXED TEACHING EXAMPLE</span><p>${esc(r.setup)}</p><strong>Expected result ≈ ${fmt(r.expected,8)}</strong><p class="sv-small">This number is for the stated example only. Changing a range does not recalculate this result; it changes the formula to paste into your workbook.</p></div>${note(r.caution)}${r.lab?`<a class="tk-text-link" href="${esc(C.labURL(r.lab,$('sv-course').value))}">Explore the matching calculation in the Statistics Lab →</a>`:''}${source(r.source,'Function / method documentation')}`;
    filterRecipes();formula();syncURL();
  }
  function formula(){try{lastFormula=F.formatFormula(F.byId.get(recipe).template,{range:$('sv-range').value,second:$('sv-second').value,separator:$('sv-separator').value,decimal:$('sv-decimal').value});$('sv-formula-output').textContent=lastFormula;$('sv-formula-error').hidden=true;$('sv-copy-formula').disabled=false;return true;}catch(e){lastFormula='';$('sv-formula-output').textContent='Correct the formula settings above.';$('sv-formula-error').textContent=e.message;$('sv-formula-error').hidden=false;$('sv-copy-formula').disabled=true;return false;}}
  function ceaPlot(r){
    const L=80,R=700,T=35,B=300,cx=(L+R)/2,cy=(T+B)/2,ex=Math.max(.1,Math.abs(r.de)*1.5),ey=Math.max(1000,Math.abs(r.dc)*1.5),x=v=>cx+v/ex*(R-L)/2,y=v=>cy-v/ey*(B-T)/2;
    const lx=r.lambda===0?ex:Math.min(ex,ey/r.lambda);
    return `<svg class="sv-plot" viewBox="0 0 760 365" role="img" aria-labelledby="sv-ce-title sv-ce-desc"><title id="sv-ce-title">Cost-effectiveness plane: option A relative to B</title><desc id="sv-ce-desc">Incremental QALYs ${fmt(r.de)}; incremental cost ${fmt(r.dc)}; threshold ${r.lambda}. ${esc(r.relation)}. Incremental net monetary benefit ${fmt(r.nmb)}.</desc><rect class="sv-grid-bg" x="${L}" y="${T}" width="${R-L}" height="${B-T}" rx="8"/><path class="sv-axis" d="M${L} ${cy}H${R}M${cx} ${T}V${B}"/><path class="sv-threshold" d="M${x(-lx)} ${y(-r.lambda*lx)}L${x(lx)} ${y(r.lambda*lx)}"/><text class="sv-axis-name" x="${cx}" y="18" text-anchor="middle">ΔCost (A − B)</text><text class="sv-axis-name" x="${cx}" y="348" text-anchor="middle">ΔQALYs (A − B) →</text><text class="sv-quad" x="${L+15}" y="${T+25}">NW · more cost / less effect</text><text class="sv-quad" x="${R-15}" y="${T+25}" text-anchor="end">NE · more cost / more effect</text><text class="sv-quad" x="${L+15}" y="${B-15}">SW · less cost / less effect</text><text class="sv-quad" x="${R-15}" y="${B-15}" text-anchor="end">SE · less cost / more effect</text><circle class="sv-dot" cx="${x(r.de)}" cy="${y(r.dc)}" r="8"/><text class="sv-axis-tick" x="${x(r.de)}" y="${y(r.dc)+(r.dc>=0?23:-15)}" text-anchor="middle">A (${fmt(r.de,3)}, ${fmt(r.dc,1)})</text>${[-1,1].map(k=>`<text class="sv-axis-tick" x="${x(k*ex)}" y="${cy+22}" text-anchor="middle">${fmt(k*ex,3)}</text><text class="sv-axis-tick" x="${cx+8}" y="${y(k*ey)+5}">${fmt(k*ey,1)}</text>`).join('')}</svg><p class="sv-small">Point: A relative to B. Dashed line: ΔCost = λ × ΔQALYs. Positive INMB is below that line. The axis ranges adapt; compare the numbers, not angles between different charts.</p>`;
  }
  function qalyPlot(r){const L=65,R=705,T=30,B=220,x=t=>L+t/r.time*(R-L),y=u=>T+(1-u)/2*(B-T);let paths=['',''];r.periods.forEach((p,i)=>{for(const [j,k]of [[0,'ua'],[1,'ub']])paths[j]+=`${i?'L':'M'}${x(p.start)} ${y(p[k])}L${x(p.end)} ${y(p[k])}`;});return `<svg class="sv-plot sv-short" viewBox="0 0 760 270" role="img" aria-label="Utility profiles for options A and B, constant within each period. A QALYs ${fmt(r.a)}, B QALYs ${fmt(r.b)}."><path class="sv-axis" d="M${L} ${y(0)}H${R}"/><path class="sv-line" d="${paths[0]}"/><path class="sv-threshold" d="${paths[1]}"/>${[-1,0,1].map(u=>`<text class="sv-axis-tick" x="45" y="${y(u)+5}" text-anchor="end">${u}</text>`).join('')}<text class="sv-axis-name" x="${L}" y="17">Utility weight</text><text class="sv-axis-tick" x="${L}" y="250">0</text><text class="sv-axis-tick" x="${R}" y="250" text-anchor="end">${fmt(r.time)} years</text></svg><p class="sv-small">Solid: A. Dashed: B. Each segment’s QALYs = width in years × its utility weight. Negative utility segments subtract QALYs.</p>`;}
  function health(){
    try{let html;
      if(healthMode==='cea'){
        const r=C.costEffectiveness({ca:read('sv-ca'),cb:read('sv-cb'),ea:read('sv-ea'),eb:read('sv-eb'),lambda:read('sv-lambda')}),currency=$('sv-currency').value==='units'?'monetary units':$('sv-currency').value;
        const pref=r.preference==='tie'?'Equal net monetary benefit (within numeric precision)':`Option ${r.preference} has higher net monetary benefit`;
        html=`<span class="sv-route-status">${esc(r.relation)}</span><h3>${pref}</h3>${ceaPlot(r)}${metrics([['Incremental cost ΔC',fmt(r.dc)+' '+currency],['Incremental QALYs ΔE',fmt(r.de)],['ICER ΔC / ΔE',r.icer===null?'Undefined · equal effects':fmt(r.icer)+' / QALY'],['Incremental NMB',fmt(r.nmb)+' '+currency]])}${step(1,'Define the comparison',`ΔC = ${r.ca} − (${r.cb}) = ${fmt(r.dc)}\nΔE = ${r.ea} − (${r.eb}) = ${fmt(r.de)}`,'The contrast is A minus B. Effects are QALYs, where higher is better. Use the same population denominator and horizon.')}${step(2,'Read the quadrant before the ratio',r.icer===null?'ΔE = 0 → ICER is undefined':`ICER = ${fmt(r.dc)} / (${fmt(r.de)}) = ${fmt(r.icer)} ${currency} per QALY`,r.de<0?'A loses health. A positive southwest ICER is savings per QALY forgone, so the familiar “ICER below threshold” rule cannot be used blindly. A negative ICER in the northwest means dominance by B.':'A negative southeast ICER reflects better outcomes at lower cost. A ratio alone does not show which quadrant applies.')}${step(3,'Value the trade-off at the chosen threshold',`INMB = λ × ΔE − ΔC\n= ${r.lambda} × (${fmt(r.de)}) − (${fmt(r.dc)})\n= ${fmt(r.nmb)} ${currency}`,`${pref}. This statement is conditional on your point estimates and illustrative λ; it is not a recommendation to adopt a treatment.`)}<details class="sv-sensitivity"><summary>Explore threshold sensitivity (other inputs held fixed)</summary><div class="sv-table-scroll"><table><thead><tr><th>λ / QALY</th><th>INMB</th><th>Higher NMB</th></tr></thead><tbody>${[0,.5,1,1.5,2].map(m=>{const t=r.lambda*m,nmb=t*r.de-r.dc;return `<tr><td>${fmt(t)}</td><td>${fmt(nmb)}</td><td>${Math.abs(nmb)<1e-8?'Tie':nmb>0?'A':'B'}</td></tr>`;}).join('')}</tbody></table></div><p class="sv-small">This varies only the decision threshold. It is not a probabilistic analysis or a probability of cost-effectiveness.</p></details>${note('No official λ is assumed. Cost-effectiveness, affordability, clinical suitability and equity are different questions. This two-option model does not assess multiple-option extended dominance.')}${source(C.refs.nmb,'York Health Economics Consortium: net monetary benefit')}`;
      }else if(healthMode==='qaly'){
        const r=C.qaly(C.parseRows($('sv-qaly-data').value,3,30));lastQALY=r;
        html=`<h3>Health-adjusted time, made explicit.</h3>${qalyPlot(r)}${metrics([['Horizon',fmt(r.time)+' years'],['Option A QALYs',fmt(r.a)],['Option B QALYs',fmt(r.b)],['Incremental QALYs',fmt(r.difference)]])}<div class="sv-table-scroll"><table><thead><tr><th>Period</th><th>Years</th><th>Utility A</th><th>Utility B</th><th>QALYs A</th><th>QALYs B</th></tr></thead><tbody>${r.periods.map(p=>`<tr><td>${p.period}</td><td>${fmt(p.years)}</td><td>${fmt(p.ua)}</td><td>${fmt(p.ub)}</td><td>${fmt(p.qa)}</td><td>${fmt(p.qb)}</td></tr>`).join('')}</tbody></table></div>${step(1,'Integrate constant-state utility over time',`QALYs A = Σ(years × utility A) = ${fmt(r.a)}\nQALYs B = Σ(years × utility B) = ${fmt(r.b)}\nΔQALYs = ${fmt(r.difference)}`,'Each row is a consecutive time period shared by both options. These are undiscounted values. Do not confuse a utility weight with a duration or a QALY total.')}${note('A constant-within-period teaching model. No mortality model, baseline adjustment, uncertainty interval or discounting is included. Use these QALYs in the comparison only when its costs use the same horizon and basis.')}${source(C.refs.qaly,'York Health Economics Consortium: QALYs')}`;
      }else{
        const r=C.discount(C.parseRows($('sv-discount-data').value,3),read('sv-rc')/100,read('sv-re')/100);
        html=`<h3>Put future values on a common time basis.</h3>${metrics([['Undiscounted costs',fmt(r.rawCost)],['Present-value costs',fmt(r.cost)],['Undiscounted QALYs',fmt(r.rawEffect)],['Present-value QALYs',fmt(r.effect)]])}<div class="sv-table-scroll"><table><thead><tr><th>Year t</th><th>Cost</th><th>PV cost</th><th>QALYs</th><th>PV QALYs</th></tr></thead><tbody>${r.rows.map(p=>`<tr><td>${p.year}</td><td>${fmt(p.cost)}</td><td>${fmt(p.pvCost)}</td><td>${fmt(p.effect)}</td><td>${fmt(p.pvEffect)}</td></tr>`).join('')}</tbody></table></div>${step(1,'Discount each dated flow separately',`PV(cost) = Σ Cₜ / (1 + ${r.rc})ᵗ = ${fmt(r.cost)}\nPV(QALYs) = Σ Eₜ / (1 + ${r.re})ᵗ = ${fmt(r.effect)}`,'The rate is per year, and t is elapsed years. An amount at t=0 retains its full value. No rate is automatically selected for a country or agency.')}${step(2,'Check timing in Excel','For yearly end-period costs C₁,…,Cₙ:\n=C₀+NPV(rate,C₁_range_through_Cₙ)','Excel NPV discounts its first listed amount by one period. Keep time-zero flows outside NPV. Missing years in a table are not collapsed into consecutive dates by this tool.')}${note('These are present-value totals, not a cost-effectiveness verdict, a budget-impact model or a survival-adjusted QALY model. Enter comparable discounted totals into a separate A-versus-B analysis only after checking the time horizon.')}${source(C.refs.npv,'Microsoft: NPV and timing')}`;
      }
      $('sv-health-result').innerHTML=html;$('sv-health-error').hidden=true;lastEconValid=true;$('sv-copy-working').disabled=false;$('sv-apply-qaly').hidden=healthMode!=='qaly';$('sv-status').textContent='Calculation updated. '+$('sv-health-result').querySelector('h3').textContent;return true;
    }catch(e){$('sv-health-error').textContent=e.message;$('sv-health-error').hidden=false;$('sv-health-result').replaceChildren();lastEconValid=false;$('sv-copy-working').disabled=true;$('sv-apply-qaly').hidden=true;return false;}
  }
  function setHealth(mode){healthMode=['cea','qaly','discount'].includes(mode)?mode:'cea';for(const m of ['cea','qaly','discount']){$('sv-'+m+'-form').hidden=m!==healthMode;root.querySelector(`[data-health="${m}"]`).setAttribute('aria-pressed',String(m===healthMode));}health();syncURL();}
  async function copy(text,opener){$('sv-clipboard').hidden=true;try{if(!navigator.clipboard||!window.isSecureContext)throw new Error();await navigator.clipboard.writeText(text);$('sv-status').textContent='Copied.';}catch(_){$('sv-clipboard').hidden=false;$('sv-copy-text').value=text;$('sv-copy-text').focus();$('sv-copy-text').select();$('sv-status').textContent='Select and copy the text below.';}if(opener)lastCopyOpener=opener;}
  let lastCopyOpener=$('sv-copy-link');
  $('sv-copy-close').addEventListener('click',()=>{$('sv-clipboard').hidden=true;lastCopyOpener?.focus();});
  const scenarios={base:[14000,10000,2.4,2,20000],dominant:[8000,10000,2.4,2,20000],dominated:[14000,10000,1.6,2,20000],southwest:[8000,10000,1.8,2,20000]};
  function findIntents(){const rows=C.matchIntent($('sv-question').value);$('sv-matches').innerHTML=rows.length?`<p class="sv-small">Possible starting points — confirm the assumptions in the tool.</p><div class="sv-match-list">${rows.map(r=>r.target==='lab'?`<a href="${esc(C.labURL(r.tool,$('sv-course').value))}">${esc(r.title)} →</a>`:`<button type="button" data-intent="${r.id}">${esc(r.title)} →</button>`).join('')}</div>`:'<p class="sv-small">No topic match yet. Choose one of the three tools below; this search does not interpret arbitrary equations.</p>';}
  $('sv-question-form').addEventListener('submit',e=>{e.preventDefault();findIntents();});
  root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
    if(b.dataset.solver)setSolver(b.dataset.solver,true);
    if(b.dataset.health)setHealth(b.dataset.health);
    if(b.dataset.recipe){selectRecipe(b.dataset.recipe);$('sv-formula-output').focus();}
    if(b.dataset.prompt){$('sv-question').value=b.dataset.prompt;findIntents();}
    if(b.dataset.intent){const r=C.intents.find(r=>r.id===b.dataset.intent);if(!r)return;setSolver(r.target,true);if(r.preset==='paired'){$('sv-groups').value='two';$('sv-design').value='paired';$('sv-outcome').value='numeric';$('sv-goal').value='test';finder();}else if(r.target==='health')setHealth(r.preset||'cea');}
    if(b.dataset.scenario){['ca','cb','ea','eb','lambda'].forEach((k,i)=>$('sv-'+k).value=scenarios[b.dataset.scenario][i]);health();}
  });
  $('sv-finder-form').addEventListener('submit',e=>{e.preventDefault();finder();});$('sv-finder-form').addEventListener('change',finder);$('sv-finder-form').addEventListener('input',finder);
  $('sv-formula-search').addEventListener('input',filterRecipes);$('sv-formula-category').addEventListener('change',filterRecipes);
  $('sv-formula-form').addEventListener('submit',e=>{e.preventDefault();formula();});$('sv-formula-form').addEventListener('input',formula);$('sv-formula-form').addEventListener('change',formula);
  $('sv-copy-formula').addEventListener('click',e=>{if(formula())copy(lastFormula,e.target);});
  $('sv-copy-data').addEventListener('click',e=>{copy('12\t11\n14\t13\n14\t15\n17\t16\n21\t20\n24\t23\n28\t27',e.target);$('sv-status').textContent='Example columns A and B prepared. Paste at A2 (no headers). The formula example explains the meaning of each column.';});
  for(const mode of ['cea','qaly','discount']){const form=$('sv-'+mode+'-form');form.addEventListener('submit',e=>{e.preventDefault();health();});form.addEventListener('input',health);form.addEventListener('change',health);}
  $('sv-health-calculate').addEventListener('click',health);
  $('sv-copy-working').addEventListener('click',e=>{if(health())copy('EU-HEM Student Toolkit — '+healthMode+'\n\n'+$('sv-health-result').innerText+'\n\nEducational model only. Inputs stay in this page until you copy them.',e.target);});
  $('sv-apply-qaly').addEventListener('click',()=>{if(healthMode!=='qaly'||!health()||!lastQALY)return;$('sv-ea').value=lastQALY.a;$('sv-eb').value=lastQALY.b;setHealth('cea');$('sv-status').textContent='Undiscounted QALYs transferred. Costs and threshold were not changed: verify the horizon and basis before interpreting the comparison.';$('sv-ca').focus();});
  $('sv-copy-link').addEventListener('click',e=>{const url=new URL('toolkit.html',location.href);url.searchParams.set('section','solve');url.searchParams.set('solver',solver);if(solver==='excel')url.searchParams.set('recipe',recipe);if(solver==='health')url.searchParams.set('mode',healthMode);copy(url.href,e.target);});
  $('sv-print').addEventListener('click',()=>window.print());
  const exercises=[
    {q:'A single independent normal sample has n = 25. Population σ is unknown, and sample s is reported. Which reference fits a test of its mean?',options:['Known-SD z automatically','Student t with df = 24','Two-independent-means test'],correct:1,why:'With unknown population SD, the normal-population one-sample procedure uses sample s and df = n − 1. n = 25 is not a reason to treat s as a known σ.'},
    {q:'CONFIDENCE.T(0.05,10,25) returns about 4.1278. What is this value?',options:['A p-value','The lower endpoint','The margin of error'],correct:2,why:'It is the half-width. For sample mean 70, calculate 70 ± 4.1278; the function does not return the two endpoints.'},
    {q:'A costs 8000 with 1.8 QALYs; B costs 10000 with 2 QALYs. At λ = 20000, what is incremental NMB for A versus B?',options:['−2000; B has higher NMB','+2000; A dominates','10000; always adopt A'],correct:0,why:'ΔC = −2000 and ΔE = −0.2. INMB = 20000 × (−0.2) − (−2000) = −2000. The positive ICER 10000 here is savings per QALY lost, not a northeast gains-per-cost comparison.'}
  ];
  $('sv-practice-items').innerHTML=exercises.map((x,i)=>`<form class="sv-quiz" data-exercise="${i}"><fieldset><legend>${i+1}. ${esc(x.q)}</legend>${x.options.map((o,j)=>`<label><input type="radio" name="exercise-${i}" value="${j}"> ${esc(o)}</label>`).join('')}</fieldset><button type="submit" class="tk-text-button">Check &amp; explain</button><p class="sv-answer" role="status"></p></form>`).join('');
  root.querySelectorAll('.sv-quiz').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();const x=exercises[Number(form.dataset.exercise)],selected=form.querySelector('input:checked'),out=form.querySelector('.sv-answer');out.textContent=selected?(Number(selected.value)===x.correct?'Correct. ':'Not quite. ')+x.why:'Choose an answer first.';}));
  function fromURL(){const p=new URLSearchParams(location.search);if(p.get('section')!=='solve')return;setSolver(Object.hasOwn(solverNames,p.get('solver'))?p.get('solver'):'finder');if(solver==='excel')selectRecipe(p.get('recipe')||recipe);if(solver==='health')setHealth(p.get('mode')||healthMode);}
  window.addEventListener('popstate',fromURL);
  document.getElementById('toolkit-main').addEventListener('toolkit:section',e=>{if(e.detail.section==='solve')fromURL();});
  finder();selectRecipe(F.byId.has(query.get('recipe'))?query.get('recipe'):'normal-between');setHealth(query.get('mode')||'cea');booting=false;fromURL();
})();
