'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const I=require('../statistics-lab-inference-math.js'),M=require('../statistics-lab-tools-math.js');
const near=(a,b,tol=1e-10)=>assert.ok(Math.abs(a-b)<=tol,`${a} != ${b}`);
const mean={mean:75,nullMean:70,sd:4.898979485566356,n:8};
const prop={n:200,k:120,nullProportion:.5};
const two={mean1:125,mean2:129,sd1:12,sd2:15,n1:160,n2:180};
test('Mean t example and z option use different references',()=>{const t=I.meanTest(mean),z=I.meanTest({...mean,method:'z'});near(t.statistic,2.886751345948129);near(t.p,.023424636054437457);assert.equal(t.df,7);assert.ok(t.p>z.p);assert.equal(z.df,null);});
test('Mean alternatives choose direction before results',()=>{const two=I.meanTest(mean),right=I.meanTest({...mean,alternative:'greater'}),left=I.meanTest({...mean,alternative:'less'});near(right.p,two.p/2);near(left.p+right.p,1);assert.equal(left.reject,false);assert.equal(right.reject,true);});
test('Null mean equality gives p=1 for two tails',()=>{const r=I.meanTest({...mean,mean:70});assert.equal(r.statistic,0);assert.equal(r.p,1);assert.equal(r.decision,'Do not reject H₀');});
test('Large-sample estimated SD approximation is explicit and guarded',()=>{assert.throws(()=>I.meanTest({...mean,n:119,method:'large-z'}));const r=I.meanTest({...mean,n:120,method:'large-z'});assert.equal(r.df,null);assert.match(r.warning,/approximation/);});
test('Mean validation rejects empty, non-finite and impossible input',()=>{for(const v of [{n:1},{sd:0},{sd:-1},{mean:NaN},{mean:'75'},{nullMean:Infinity},{method:'bad'},{alternative:'bad'},{alpha:0},{n:1.5},{n:10002}])assert.throws(()=>I.meanTest({...mean,...v}));});
test('Boundary is not silently rounded into rejection',()=>{const statistic=M.normalInv(.975);const r=I.reference(statistic,.05,'two');assert.equal(r.boundary,true);assert.match(r.decision,/boundary/);});
test('Wald original example',()=>{const r=I.proportionCI({n:200,k:120});near(r.estimate,.6);near(r.se,Math.sqrt(.24/200));near(r.lower,.5321048559554297);near(r.upper,.6678951440445703);assert.equal(r.warnings.length,0);});
test('Wald observed count guard differs from null expected count guard',()=>{assert.throws(()=>I.proportionCI({n:100,k:1}));assert.doesNotThrow(()=>I.proportionTest({n:100,k:1,nullProportion:.5}));assert.throws(()=>I.proportionTest({n:100,k:50,nullProportion:.001}));});
test('Wald out-of-range bounds are not clipped',()=>{const r=I.proportionCI({n:100,k:5,level:.999});assert.ok(r.lower<0);assert.match(r.warnings.join(' '),/not truncated/);});
test('Wilson all-failure and all-success endpoints',()=>{const zero=I.proportionCI({n:10,k:0,method:'wilson'}),one=I.proportionCI({n:10,k:10,method:'wilson'});assert.equal(zero.lower,0);assert.equal(one.upper,1);near(zero.upper,1-one.lower);assert.ok(zero.upper>0);assert.match(zero.warnings.join(' '),/supplementary/);});
test('Wilson reference example and asymmetry',()=>{const r=I.proportionCI({n:200,k:26,method:'wilson'});near(r.lower,.0902820227966932,1e-8);near(r.upper,.18366351872248407,1e-8);assert.notEqual(r.centre,r.estimate);});
test('Proportion interval validation',()=>{for(const v of [{k:201},{k:-1},{k:1.5},{n:0},{level:1},{level:.4},{method:'bad'}])assert.throws(()=>I.proportionCI({n:200,k:120,...v}));});
test('Proportion test null-based SE and expected counts',()=>{const r=I.proportionTest(prop);near(r.se,.035355339059327376);near(r.statistic,2.82842712474619);near(r.p,.004677734981047271);assert.equal(r.expectedSuccess,100);assert.equal(r.expectedFailure,100);});
test('Proportion one-sided alternatives and complement',()=>{const r=I.proportionTest({...prop,alternative:'greater'}),l=I.proportionTest({...prop,alternative:'less'});near(r.p+l.p,1);near(2*r.p,I.proportionTest(prop).p);});
test('Null proportion endpoints and invalid counts rejected',()=>{for(const nullProportion of [0,1,-1,NaN,'0.5'])assert.throws(()=>I.proportionTest({...prop,nullProportion}));assert.throws(()=>I.proportionTest({...prop,k:201}));});
test('Two-means course recipe from existing notes',()=>{const r=I.twoMeans(two);near(r.se,Math.sqrt(2.15));near(r.statistic,-4/Math.sqrt(2.15));near(r.p,.006372398187870522,1e-8);assert.equal(r.df,null);assert.ok(r.upper<0);});
test('Reversing groups reverses interval and preserves two-tail p',()=>{const a=I.twoMeans(two),b=I.twoMeans({mean1:129,mean2:125,sd1:15,sd2:12,n1:180,n2:160});near(a.p,b.p);near(a.lower,-b.upper);});
test('Welch supports fractional df, and does not replace course default',()=>{const r=I.twoMeans({...two,method:'welch'});assert.ok(r.df>300&&r.df<338);assert.ok(!Number.isInteger(r.df));assert.match(r.warning,/Supplementary/);assert.ok(r.p>I.twoMeans(two).p);});
test('Two means n guards and paired misuse is not inferred',()=>{assert.throws(()=>I.twoMeans({...two,n1:29}));assert.doesNotThrow(()=>I.twoMeans({...two,n1:8,n2:10,method:'welch'}));assert.throws(()=>I.twoMeans({...two,method:'paired'}));});
test('Two-means nonzero null difference and one-tail result',()=>{const r=I.twoMeans({...two,nullDifference:-4});assert.equal(r.statistic,0);assert.equal(r.p,1);const greater=I.twoMeans({...two,alternative:'greater'});assert.ok(greater.p>.99);});
test('Welch upper limit stays inside shared t core',()=>{const r=I.twoMeans({...two,sd1:1,sd2:1,n1:5001,n2:5001,method:'welch'});near(r.df,10000,1e-10);});
test('Discrete model moments and inclusive event',()=>{const r=I.discrete(I.parseDistribution('0, 0.2\n1, 0.5\n2, 0.3'),'between',1,2);near(r.mean,1.1);near(r.variance,.49);near(r.sd,.7);near(r.probability,.8);near(r.table.at(-1).cumulative,1);});
test('Bernoulli moments',()=>{const r=I.discrete([{x:0,p:.7},{x:1,p:.3}],'equal',1);near(r.mean,.3);near(r.variance,.21);near(r.probability,.3);});
test('Discrete endpoint inclusion is not continuous inclusion',()=>{const rows=[{x:0,p:.2},{x:1,p:.5},{x:2,p:.3}];near(I.discrete(rows,'left',0,1).probability,.7);near(I.discrete(rows,'right',1,0).probability,.8);near(I.discrete(rows,'equal',1,1).probability,.5);near(I.discrete(rows,'equal',1.5,0).probability,0);});
test('Discrete model rejects bad totals, probabilities and duplicates',()=>{for(const rows of [[{x:0,p:.2}],[{x:1,p:1.1}],[{x:1,p:.5},{x:1,p:.5}],[{x:Infinity,p:1}],[]])assert.throws(()=>I.discrete(rows));});
test('Discrete parser strictness',()=>{for(const s of ['', 'x,p\n1,1','1,,.5','1 .5 .2','<img>,1','1,Infinity'])assert.throws(()=>I.parseDistribution(s));assert.deepEqual(I.parseDistribution('-1; .4\n2\t.6'),[{x:-1,p:.4},{x:2,p:.6}]);});
test('No input mutation by any calculator',()=>{const a={...mean},b=[{x:2,p:.3},{x:1,p:.7}];I.meanTest(a);I.discrete(b);assert.deepEqual(a,mean);assert.equal(b[0].x,2);});
