// ===== Thesis enrichment review sheet =====
// Writes docs/thesis-review.md: every classified thesis (least confident first), the disagreements
// with the independent second pass (docs/thesis-review-pass2.json), the theme -> track table and the
// resulting counts. Use it to review classifications, then mark entries "reviewed" in
// content/thesis-enrichment.json.
//
// Run: node scripts/thesis-review.js

const fs = require("fs");
const path = require("path");
global.readStorage = () => null;
global.simplify = (text) => String(text).normalize("NFD").replace(/[̀-ͯ]/g, "").toLowerCase();
global.searchText = (text) => global.simplify(text).replace(/[^a-z0-9]+/g, " ").trim();
const tracks = require("../tracks-data.js");
global.trackCourses = tracks.trackCourses;
global.courseInfo = tracks.courseInfo;
const enrich = require("../thesis-enrichment.js");

const ROOT = path.join(__dirname, "..");
const read = (file) => JSON.parse(fs.readFileSync(path.join(ROOT, file), "utf8"));

function main() {
  const archive = read("content/thesis-archive.json");
  const enrichment = read("content/thesis-enrichment.json");
  const cohort = tracks.tracksCohort(read("content/tracks.json"));
  const pass2File = path.join(ROOT, "docs", "thesis-review-pass2.json");
  const pass2 = fs.existsSync(pass2File) ? Object.fromEntries(JSON.parse(fs.readFileSync(pass2File, "utf8")).records.map((r) => [r.id, r])) : {};
  const themes = enrich.topicThemes(enrichment, cohort);
  const label = (id) => (themes.find((t) => t.id === id) || {}).label || id;
  const method = (id) => (enrichment.methods.find((m) => m.id === id) || {}).label || id;
  const trackIds = cohort.tracks.map((t) => t.id);
  const abbr = Object.fromEntries(cohort.tracks.map((t) => [t.id, t.abbr]));
  const visible = new Set(archive.records.map((r) => r.id));
  const entries = enrichment.records.filter((e) => visible.has(e.id));
  const order = { uncertain: 0, medium: 1, high: 2 };
  const cell = (text) => String(text).replace(/\|/g, "\\|");

  const lines = [];
  lines.push("# Thesis classification: review sheet");
  lines.push("");
  lines.push("_Generated by `node scripts/thesis-review.js` from content/thesis-enrichment.json. Do not edit this file: edit the enrichment file, then generate it again._");
  lines.push("");
  lines.push(`> ${enrichment.provenance}`);
  lines.push("");
  const statusCount = entries.reduce((acc, e) => ({ ...acc, [e.status]: (acc[e.status] || 0) + 1 }), {});
  const confCount = entries.reduce((acc, e) => ({ ...acc, [e.confidence]: (acc[e.confidence] || 0) + 1 }), {});
  lines.push(`**${entries.length} classified theses.** Status: ${Object.entries(statusCount).map(([k, n]) => `${k} ${n}`).join(", ")}. Confidence: ${["high", "medium", "uncertain"].map((k) => `${k} ${confCount[k] || 0}`).join(", ")}. Unclassified: ${entries.filter((e) => e.unclassified).length}.`);
  lines.push("");

  // Counts
  lines.push("## Counts");
  lines.push("");
  lines.push("| Theme | Theses |");
  lines.push("|---|---|");
  for (const t of themes) lines.push(`| ${t.label} (\`${t.id}\`) | ${entries.filter((e) => e.themes.includes(t.id)).length} |`);
  lines.push("");
  const relevance = Object.fromEntries(entries.map((e) => [e.id, enrich.trackRelevance(e, enrichment, trackIds)]));
  lines.push("| Current track | Potentially relevant theses |");
  lines.push("|---|---|");
  for (const t of cohort.tracks) lines.push(`| ${t.name} (${t.abbr}) | ${entries.filter((e) => relevance[e.id].some((r) => r.trackId === t.id)).length} |`);
  lines.push(`| _none shown_ | ${entries.filter((e) => !relevance[e.id].length).length} |`);
  lines.push(`| _two tracks shown_ | ${entries.filter((e) => relevance[e.id].length === 2).length} |`);
  lines.push("");

  // Weights
  lines.push("## Theme → current-track weights");
  lines.push("");
  lines.push(`Rule: ${enrichment.relevance.rule}`);
  lines.push("");
  lines.push(`| Theme | ${cohort.tracks.map((t) => t.abbr).join(" | ")} | Basis |`);
  lines.push(`|---|${cohort.tracks.map(() => "---").join("|")}|---|`);
  for (const t of themes) {
    const w = enrichment.relevance.weights[t.id] || {};
    const counts = enrich.themeCourseCounts(cohort, t.id);
    lines.push(`| ${t.label} | ${trackIds.map((id) => `${w[id]} (${counts[id].required}R ${counts[id].elective}E)`).join(" | ")} | ${w.basis}${w.basis === "proposal" ? " ⚑" : ""}${w.secondary ? ", secondary" : ""} |`);
  }
  lines.push("");
  lines.push("⚑ Proposal: no course in tracks.json carries this theme, so the weights are set by hand. Secondary: adds to a score but never justifies a track on its own. R/E = required/elective courses carrying the theme.");
  lines.push("");

  // Disagreements with pass 2
  const sameSet = (a, b) => JSON.stringify([...(a || [])].sort()) === JSON.stringify([...(b || [])].sort());
  const diffs = entries.filter((e) => pass2[e.id] && (!sameSet(e.themes, pass2[e.id].themes) || !sameSet(e.statedMethods, pass2[e.id].statedMethods) || !sameSet(e.statedCountries, pass2[e.id].statedCountries)));
  lines.push(`## Disagreements with the independent second pass (${diffs.length})`);
  lines.push("");
  lines.push("The second pass was made separately, from the titles and the written rules only, without seeing the first pass. Each disagreement was then reviewed case by case; the final classification (in the file) and the reason are shown.");
  lines.push("");
  lines.push("| id | Title | Differs in | Final (in the file) | Pass 2 | Reason |");
  lines.push("|---|---|---|---|---|---|");
  const summary = (r) => [r.themes.map(label).join(", ") || "–", r.statedMethods.length ? `method: ${r.statedMethods.map(method).join(", ")}` : "", r.statedCountries.length ? `place: ${r.statedCountries.join(", ")}` : ""].filter(Boolean).join("; ");
  for (const e of diffs) {
    const o = pass2[e.id];
    const what = [!sameSet(e.themes, o.themes) && "themes", !sameSet(e.statedMethods, o.statedMethods) && "method", !sameSet(e.statedCountries, o.statedCountries) && "place"].filter(Boolean).join(", ");
    lines.push(`| ${e.id} | ${cell(e.title)} | ${what} | ${cell(summary(e))} | ${cell(summary(o))} | ${cell(e.note || "")} |`);
  }
  lines.push("");

  // All entries, least confident first
  lines.push("## All classifications (least confident first)");
  lines.push("");
  lines.push("| id | Title | Themes | Stated method | Stated places | Confidence | Potentially relevant to | Status |");
  lines.push("|---|---|---|---|---|---|---|---|");
  const sorted = [...entries].sort((a, b) => order[a.confidence] - order[b.confidence] || a.id.localeCompare(b.id));
  for (const e of sorted) {
    const rel = e.trackOverride ? `${e.trackOverride.tracks.map((id) => abbr[id]).join(", ") || "none"} (override: ${e.trackOverride.reason})` : relevance[e.id].map((r) => `${abbr[r.trackId]} (via ${label(r.because)})`).join(", ") || "–";
    lines.push(`| ${e.id} | ${cell(e.title)}${e.note ? `<br>_${cell(e.note)}_` : ""} | ${e.unclassified ? "_unclassified_" : e.themes.map(label).join(", ")} | ${e.statedMethods.map(method).join(", ") || "–"} | ${e.statedCountries.join(", ") || "–"} | ${e.confidence} | ${rel} | ${e.status} |`);
  }
  lines.push("");
  fs.writeFileSync(path.join(ROOT, "docs", "thesis-review.md"), lines.join("\n"));
  console.log(`✔ Wrote docs/thesis-review.md: ${entries.length} theses, ${diffs.length} disagreements with the second pass.`);
}

if (require.main === module) main();
