// Mocked services only: all releases, Now paging, dates, sources, subscriptions and layout.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require('playwright');
const ROOT=path.resolve(process.argv[2]||'.'),SHOTS=process.env.SCREENSHOT_DIR;
const MIME={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.csv':'text/csv','.svg':'image/svg+xml','.woff2':'font/woff2','.png':'image/png','.webp':'image/webp','.jpg':'image/jpeg'};
(async()=>{
 if(SHOTS)fs.mkdirSync(SHOTS,{recursive:true});
 const server=http.createServer((req,res)=>{const file=path.resolve(ROOT,new URL(req.url,'http://localhost').pathname.replace(/^\/eu-hem-student-hub\//,''));if(!file.startsWith(ROOT+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);return res.end('missing');}res.writeHead(200,{'Content-Type':MIME[path.extname(file)]||'text/plain'});res.end(fs.readFileSync(file));});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}/eu-hem-student-hub/`;
 const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH||undefined,args:['--no-sandbox']});
 let checks=0;const errors=[],ok=label=>{checks++;console.log('ok '+label);};
 async function open(file,options={}){
  const context=await browser.newContext({viewport:{width:options.width||1440,height:1000},colorScheme:options.scheme||'light',timezoneId:'America/Los_Angeles',serviceWorkers:'block',reducedMotion:'reduce'});
  await context.addInitScript(storage=>Object.entries(storage).forEach(([k,v])=>localStorage.setItem(k,v)),options.storage||{});
  let failed=false;
  await context.route('**/*',route=>{const url=route.request().url();if(!url.startsWith(base))return route.abort();if(options.fail&&!failed&&url.endsWith(options.fail)){failed=true;return route.fulfill({status:503,body:'unavailable'});}if(options.noData&&/content\/(roadmap|updates)\.json/.test(url))return route.fulfill({status:503,body:'unavailable'});if(url.endsWith('data/events.json'))return route.fulfill({status:404,body:'unconnected'});return route.continue();});
  const page=await context.newPage();page.setDefaultTimeout(15000);await page.clock.setFixedTime(new Date('2026-10-10T00:10:00+02:00'));page.on('pageerror',e=>{errors.push(e.message);console.error('PAGE ERROR: '+e.message);});await page.goto(base+file);return {page,context};
 }
 const overflow=async page=>assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'no horizontal page overflow');
 async function capture(page,name,locator){if(!SHOTS)return;await page.evaluate(()=>document.fonts.ready);if(locator)await page.locator(locator).screenshot({path:path.join(SHOTS,name+'.png')});else await page.screenshot({path:path.join(SHOTS,name+'.png'),fullPage:true});}
 try{
  const updates=require(path.join(ROOT,'roadmap-data.js')).publishedUpdates(JSON.parse(fs.readFileSync(path.join(ROOT,'content/updates.json'),'utf8')));
  let {page,context}=await open('index.html');await page.locator('.roadmap-preview-now').waitFor();const before=await page.locator('.roadmap-preview-latest').boundingBox(),seen=new Set();
  for(let n=0;n<Math.ceil(updates.length/3);n++){for(const href of await page.locator('.home-release-window a').evaluateAll(a=>a.map(x=>x.getAttribute('href'))))seen.add(href);const older=page.getByRole('button',{name:'Older releases'});if(await older.getAttribute('aria-disabled')==='true')break;await older.click();assert.equal(await older.evaluate(n=>n===document.activeElement),true);assert.equal((await page.locator('.roadmap-preview-latest').boundingBox()).height,before.height);}
  assert.deepEqual([...seen].sort(),updates.map(u=>'roadmap.html#update-'+u.id).sort());assert.equal(await page.getByRole('button',{name:'Older releases'}).getAttribute('aria-disabled'),'true');await page.getByRole('button',{name:'Newer releases'}).click();ok('all published releases reachable, drafts excluded, boundary arrows and stable height');
  const oldHref=await page.locator('.roadmap-preview-now').getAttribute('href'),height=(await page.locator('.home-focus-panel').boundingBox()).height;
  await page.getByRole('button',{name:'Next work in progress'}).click();assert.notEqual(await page.locator('.roadmap-preview-now').getAttribute('href'),oldHref);assert.match(await page.locator('.roadmap-preview-now').textContent(),/Beta|v1\.0|launch/i);assert.equal((await page.locator('.home-focus-panel').boundingBox()).height,height);await page.getByRole('button',{name:'Previous work in progress'}).click();assert.equal(await page.locator('.roadmap-preview-now').getAttribute('href'),oldHref);await capture(page,'homepage-pagers','#home-roadmap');await context.close();ok('both Now items work without nested buttons or resizing');
  ({page,context}=await open('index.html',{noData:true}));await page.locator('#home-roadmap').waitFor({state:'hidden'});assert.equal(await page.locator('#latest-announcements').isVisible(),true);await context.close();ok('roadmap failure does not hide the announcements');
  ({page,context}=await open('calendar.html'));await page.locator('.key-date').first().waitFor();assert.equal(await page.locator('.key-date').count(),10);assert.equal(await page.locator('#key-dates-list .source-badge.is-official').count(),10);assert.equal(await page.locator('[aria-current="date"]').getAttribute('data-date'),'2026-10-10');assert.match(await page.locator('#calendar-highlight').textContent(),/26 Oct – 7 Nov 2026/);
  await page.getByRole('button',{name:'Exams',exact:true}).click();assert.equal(await page.locator('.key-date').count(),3);await page.locator('#key-date-search').fill('Re-sit');assert.equal(await page.locator('.key-date').count(),1);await page.locator('#key-date-reset').click();assert.equal(await page.locator('.key-date').count(),10);await page.locator('[data-date="2026-10-27"]').click();assert.equal(await page.locator('.key-date').count(),1);assert.match(await page.locator('#key-dates-list').textContent(),/Exams, first term/);await page.locator('[data-date="2026-10-27"]').press('ArrowRight');assert.equal(await page.evaluate(()=>document.activeElement.dataset.date),'2026-10-28');await page.locator('#key-date-reset').click();ok('sources, intersecting filters, selected-day details and Bologna-time keyboard calendar');
  for(let n=0;n<3;n++)await page.locator('#key-month-next').click();assert.match(await page.locator('#key-month-title').textContent(),/January 2027/);assert.match(await page.locator('#key-month-approximate').textContent(),/Erasmus/);assert.doesNotMatch(await page.locator('[data-date="2027-01-12"]').getAttribute('aria-label'),/Erasmus/);await page.locator('#key-month-today').click();
  await page.locator('#key-date-search').fill('not-present');assert.equal(await page.locator('.key-date').count(),0);await page.evaluate(()=>window.dispatchEvent(new Event('beforeprint')));assert.equal(await page.locator('.key-date').count(),10);await page.evaluate(()=>window.dispatchEvent(new Event('afterprint')));assert.equal(await page.locator('.key-date').count(),0);await page.locator('#key-date-reset').click();ok('approximate windows are never exact appointments; print restores the filter');
  await page.locator('#calendar-links').waitFor({state:'visible'});const url=await page.locator('#calendar-url').inputValue();assert.match(url,/\/calendar\/eu-hem-2026-27-year1\.ics$/);assert.equal(await page.locator('#calendar-apple').getAttribute('href'),url.replace('http:','webcal:'));await page.locator('.calendar-copy-details summary').click();await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{value:{writeText:()=>Promise.reject(new Error('fixture'))},configurable:true}));await page.locator('#calendar-copy').click();assert.match(await page.locator('#calendar-copy-status').textContent(),/selected/);assert.equal(await page.evaluate(()=>document.activeElement.id),'calendar-url');await capture(page,'calendar-desktop');await context.close();ok('subscription URLs and accessible manual-copy fallback');
  for(const file of ['calendar/calendars.json','content/programme.json']){({page,context}=await open('calendar.html',{fail:file}));if(file.includes('programme')){await page.locator('#key-date-retry').waitFor({state:'visible'});await page.locator('#key-date-retry').click();await page.locator('.key-date').first().waitFor();}await page.waitForFunction(()=>!document.getElementById('calendar-links').hidden||!document.getElementById('calendar-retry').hidden);if(await page.locator('#calendar-retry').isVisible()){await page.locator('#calendar-retry').click();}else assert.ok(file.includes('programme'),'a failed calendars index must expose its retry');await page.locator('#calendar-links').waitFor({state:'visible'});await context.close();}ok('feed/programme failures recover through explicit retries');
  const plan=JSON.stringify({version:1,cohort:'2026-27',term:'y1-s1',choices:{quant:'96525',elective:'C8393'},statuses:{},savedAt:'2026-10-01T00:00:00Z'});({page,context}=await open('calendar.html',{storage:{'euhem-study-plan-v1':plan}}));await page.locator('#calendar-links').waitFor({state:'visible'});assert.match(await page.locator('#calendar-url').inputValue(),/96525-C8393\.ics$/);assert.match(await page.locator('#calendar-plan-note').textContent(),/Only the courses/);await context.close();ok('saved-plan subscription selection is preserved');
  for(const width of [320,390,768,1440])for(const scheme of ['light','dark']){
   ({page,context}=await open('calendar.html',{width,scheme}));await page.locator('.key-date').first().waitFor();await overflow(page);await page.locator('.calendar-copy-details summary').click();await overflow(page);for(const summary of await page.locator('#calendar-help summary').all())await summary.click();await overflow(page);if(width===390)await capture(page,'calendar-phone-'+scheme);await context.close();
   ({page,context}=await open('index.html',{width,scheme}));await page.locator('.roadmap-preview-now').waitFor();await page.getByRole('button',{name:'Next work in progress'}).click();await page.getByRole('button',{name:'Older releases'}).click();await overflow(page);if(width===390)await capture(page,'homepage-phone-'+scheme,'#home-roadmap');await context.close();
  }ok('four viewport widths, two themes, expanded help and both homepage browsers');assert.deepEqual(errors,[]);ok('no uncaught JavaScript errors');console.log(`${checks} home/calendar browser groups passed`);
 }finally{await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1;});
